{% set data = load_setup_py_data() %}

package:
  name: rsml
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} setup.py install #--single-version-externally-managed --record=record.txt

requirements:
  build:
    - python  {{PY_VER}}
    - openalea.deploy
  run:
    - python >=3.6
    - openalea.mtg
    - matplotlib

test:
  requires:
    - pytest 
  imports:
    - rsml
  source_files:
    - share/data/**
    - test/**
  commands:
    - cd test
    - pytest -v 

about:
  home: http://github.com/openalea/RSML
  license: Cecill-c License
  summary: RSML - The language of root architecture

